const layouts = {
  'default.set': 'Default Set',
  'famous.set': 'Famous Latin Layouts',
  'standard.tarmak.set': 'Tarmak Set',
  'standard.tarmak_dh.set': 'Tarmak-DH Set',
  'european.tarmak_dh.set': 'Tarmak-DH ISO Set',
  'standard.russian-alternatives.set': 'Russian Layouts',
  'Latin: ANSI Keyboards': {
    'standard.abcdef': 'ABCDEF',
    'standard.arensito': 'Arensito',
    'standard.adnw': 'AdnW',
    'standard.asset': 'Asset',
    'standard.capewell': 'Capewell',
    'standard.carpalxq': 'CarpalxQ',
    'standard.colemak': 'Colemak',
    'standard.colemak_dh': 'Colemak-DH (Mod-DH)',
    'standard.simplifiedDvorak': 'Dvorak (Simplified)',
    'standard.programmerDvorak': 'Dvorak (Programmer)',
    'standard.spanish-dvorak': 'Dvorak (Spanish)',
    'standard.ohdvorakl': 'One-handed Dvorak (Left)',
    'standard.ohdvorakr': 'One-handed Dvorak (Right)',
    'standard.klausler': 'Klausler',
    'standard.minimak8key': 'Minimak 8-key',
    'standard.minimak12key': 'Minimak 12-key',
    'standard.mtgap': 'MTGAP',
    'standard.neo2': 'Neo 2 (v1)',
    'standard.neo2_new': 'Neo 2 (v2)',
    'standard.niro': 'Niro',
    'standard.norman': 'Norman',
    'standard.qgmlwy': 'QGMLWY',
    'standard.qwerfj': 'QWERFJ',
    'standard.qwerty': 'QWERTY',
    'standard.qwertywm': 'QWERTY – Wide Mod',
    'standard.qwpr': 'QWPR',
    'standard.soul': 'Soul',
    'standard.tnwmlc': 'TNWMLC (Worst CarpalX layout)',
    'standard.workman': 'Workman',
  },
  'Latin: ISO Keyboards': {
    'european.azerty': 'AZERTY',
    'european.bepo': 'BÉPO',
    'european.colemak': 'Colemak',
    'european_ss.colemak': 'Colemak split-space',
    'european.colemak_dh': 'Colemak-DH (Mod-DH)',
    'european_ss.colemak_dh': 'Colemak-DH (Mod-DH) split-space',
    'european_ss.norman_kripo_programmer': 'Norman KRIPO (Programmer)',
    'european.qwerty': 'QWERTY',
    'european_ss.qwerty': 'QWERTY split-space',
    'european.qwerty-spanish': 'QWERTY (Spanish)',
    'european.qwerty-estonian': 'QWERTY (Estonian)',
  },
  'Latin: Matrix Keyboards': {
    'matrix.colemak': 'Colemak',
    'matrix.colemak_dh': 'Colemak-DH (Mod-DH)',
    'matrix.dvorak': 'Dvorak',
    'matrix.norman': 'Norman',
    'matrix.qwerty': 'QWERTY',
    'matrix.workman': 'Workman',
  },
  'Latin: Ergodox Keyboards': {
    'ergodox.colemak': 'Colemak',
    'ergodox.colemak-thumbshift': 'Colemak thumbshift',
    'ergodox.kinesis-advantage-colemak': 'Colemak (Kinesis Advantage)',
    'ergodox.colemak_dh': 'Colemak-DH (Mod-DH) thumbshift',
    'ergodox.maltron': 'Maltron',
    'ergodox.mtgap': 'MTGAP',
    'ergodox.mtgap-thumbshift': 'MTGAP thumbshift',
    'ergodox.norman': 'Norman',
    'ergodox.qgmlwbcub': 'QGMLWB',
    'ergodox.qgmlwycub': 'QGMLWY',
    'ergodox.qwerty': 'QWERTY',
    'ergodox.qwerty-thumbshift': 'QWERTY thumbshift',
    'ergodox.rsthd': 'RSTHD',
    'ergodox.workman': 'Workman',
  },
  'Cyrillic': {
    'standard.bulgarian': 'Bulgarian',
    'standard.russian_diktor': 'Diktor',
    'standard.russian_zubachev': 'Zubachev',
    'standard.russian': 'ЙЦУКЕН',
    'standard.russiannm': 'ЙЦУКЕН – Narrow Mod',
    'standard.russian_typewriter': 'ЙЦУКЕН (Typewriter)',
    'standard.russian_typographic': 'ЙЦУКЕН (Typographic)',
    'standard.russian_yvam-told-2': 'ЫВАМ ТОЛД 2.0',
  },
  'Fingerings': {
    'standard.classical.fingering': 'ANSI: Classical',
    'standard.classical-wide.fingering': 'ANSI: Classical Wide',
    'standard.colemak_dh.fingering': 'ANSI: Colemak-DH',
    'standard.diktor.fingering': 'ANSI: Diktor',
    'standard.shift-up.fingering': 'ANSI: Shift Up',
    'standard.symmetric-typing-project.fingering': 'ANSI: Symmetric Typing Project',
    'standard.untangled.fingering': 'ANSI: Untangled',
    'european.classical.fingering': 'ISO: Classical',
    'european.colemak_dh.fingering': 'ISO: Colemak-DH',
    'european_ss.classical.fingering': 'ISO split-space: Classical',
    'european_ss.colemak_dh.fingering': 'ISO split-space: Colemak-DH',
  },
}

export default layouts
