const layouts = {
  'default.kla-set': 'Default Set',
  'famous.kla-set': 'Famous Latin Layouts',
  'standard.tarmak.kla-set': 'Tarmak Set',
  'standard.tarmak_dh.kla-set': 'Tarmak-DH Set',
  'european.tarmak_dh.kla-set': 'Tarmak-DH ISO Set',
  'standard.russian-alternatives.kla-set': 'Russian Layouts',
  'Latin: ANSI Keyboards': {
    'standard.abcdef.kla-layout': 'ABCDEF',
    'standard.arensito.kla-layout': 'Arensito',
    'standard.adnw.kla-layout': 'AdnW',
    'standard.asset.kla-layout': 'Asset',
    'standard.capewell.kla-layout': 'Capewell',
    'standard.carpalxq.kla-layout': 'CarpalxQ',
    'standard.colemak.kla-layout': 'Colemak',
    'standard.colemak_dh.kla-layout': 'Colemak-DH (Mod-DH)',
    'standard.simplifiedDvorak.kla-layout': 'Dvorak (Simplified)',
    'standard.programmerDvorak.kla-layout': 'Dvorak (Programmer)',
    'standard.spanish-dvorak.kla-layout': 'Dvorak (Spanish)',
    'standard.ohdvorakl.kla-layout': 'One-handed Dvorak (Left)',
    'standard.ohdvorakr.kla-layout': 'One-handed Dvorak (Right)',
    'standard.klausler.kla-layout': 'Klausler',
    'standard.minimak8key.kla-layout': 'Minimak 8-key',
    'standard.minimak12key.kla-layout': 'Minimak 12-key',
    'standard.mtgap.kla-layout': 'MTGAP',
    'standard.neo2.kla-layout': 'Neo 2 (v1)',
    'standard.neo2_new.kla-layout': 'Neo 2 (v2)',
    'standard.niro.kla-layout': 'Niro',
    'standard.norman.kla-layout': 'Norman',
    'standard.qgmlwy.kla-layout': 'QGMLWY',
    'standard.qwerfj.kla-layout': 'QWERFJ',
    'standard.qwerty.kla-layout': 'QWERTY',
    'standard.qwertywm.kla-layout': 'QWERTY – Wide Mod',
    'standard.qwpr.kla-layout': 'QWPR',
    'standard.soul.kla-layout': 'Soul',
    'standard.tnwmlc.kla-layout': 'TNWMLC (Worst CarpalX layout)',
    'standard.workman.kla-layout': 'Workman',
  },
  'Latin: ISO Keyboards': {
    'european.azerty.kla-layout': 'AZERTY',
    'european.bepo.kla-layout': 'BÉPO',
    'european.colemak.kla-layout': 'Colemak',
    'european_ss.colemak.kla-layout': 'Colemak split-space',
    'european.colemak_dh.kla-layout': 'Colemak-DH (Mod-DH)',
    'european_ss.colemak_dh.kla-layout': 'Colemak-DH (Mod-DH) split-space',
    'european_ss.norman_kripo_programmer.kla-layout': 'Norman KRIPO (Programmer)',
    'european.qwerty.kla-layout': 'QWERTY',
    'european_ss.qwerty.kla-layout': 'QWERTY split-space',
    'european.qwerty-spanish.kla-layout': 'QWERTY (Spanish)',
    'european.qwerty-estonian.kla-layout': 'QWERTY (Estonian)',
  },
  'Latin: Matrix Keyboards': {
    'matrix.colemak.kla-layout': 'Colemak',
    'matrix.colemak_dh.kla-layout': 'Colemak-DH (Mod-DH)',
    'matrix.dvorak.kla-layout': 'Dvorak',
    'matrix.norman.kla-layout': 'Norman',
    'matrix.qwerty.kla-layout': 'QWERTY',
    'matrix.workman.kla-layout': 'Workman',
  },
  'Latin: Ergodox Keyboards': {
    'ergodox.colemak.kla-layout': 'Colemak',
    'ergodox.colemak-thumbshift.kla-layout': 'Colemak thumbshift',
    'ergodox.kinesis-advantage-colemak.kla-layout': 'Colemak (Kinesis Advantage)',
    'ergodox.colemak_dh.kla-layout': 'Colemak-DH (Mod-DH) thumbshift',
    'ergodox.maltron.kla-layout': 'Maltron',
    'ergodox.mtgap.kla-layout': 'MTGAP',
    'ergodox.mtgap-thumbshift.kla-layout': 'MTGAP thumbshift',
    'ergodox.norman.kla-layout': 'Norman',
    'ergodox.qgmlwbcub.kla-layout': 'QGMLWB',
    'ergodox.qgmlwycub.kla-layout': 'QGMLWY',
    'ergodox.qwerty.kla-layout': 'QWERTY',
    'ergodox.qwerty-thumbshift.kla-layout': 'QWERTY thumbshift',
    'ergodox.rsthd.kla-layout': 'RSTHD',
    'ergodox.workman.kla-layout': 'Workman',
  },
  'Cyrillic': {
    'standard.bulgarian.kla-layout': 'Bulgarian',
    'standard.russian_diktor.kla-layout': 'Diktor',
    'standard.russian_zubachev.kla-layout': 'Zubachev',
    'standard.russian.kla-layout': 'ЙЦУКЕН',
    'standard.russiannm.kla-layout': 'ЙЦУКЕН – Narrow Mod',
    'standard.russian_typewriter.kla-layout': 'ЙЦУКЕН (Typewriter)',
    'standard.russian_typographic.kla-layout': 'ЙЦУКЕН (Typographic)',
    'standard.russian_yvam-told-2.kla-layout': 'ЫВАМ ТОЛД 2.0',
  },
  'Fingerings': {
    'standard.classical.kla-fingering': 'ANSI: Classical',
    'standard.classical-wide.kla-fingering': 'ANSI: Classical Wide',
    'standard.colemak_dh.kla-fingering': 'ANSI: Colemak-DH',
    'standard.diktor.kla-fingering': 'ANSI: Diktor',
    'standard.shift-up.kla-fingering': 'ANSI: Shift Up',
    'standard.symmetric-typing-project.kla-fingering': 'ANSI: Symmetric Typing Project',
    'standard.untangled.kla-fingering': 'ANSI: Untangled',
    'european.classical.kla-fingering': 'ISO: Classical',
    'european.colemak_dh.kla-fingering': 'ISO: Colemak-DH',
    'european_ss.classical.kla-fingering': 'ISO split-space: Classical',
    'european_ss.colemak_dh.kla-fingering': 'ISO split-space: Colemak-DH',
  },
}

export default layouts
